# Generated by Django 3.0.5 on 2020-04-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='verdicts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('val', models.IntegerField()),
            ],
        ),
    ]
